version: "3"
services:
  static:
    image: __DOCKER_IMAGE_NAME__:__DOCKER_IMAGE_TAG__
    ports:
    - target: 80
      published: __PORT__
    env_file:
      - .env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 20M
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
